[workspace]
members = ["temps", "temps-core", "temps-chrono", "temps-jiff", "temps-testhelpers"]
resolver = "3"

[workspace.package]
version = "2.0.2"
edition = "2024"
authors = ["Stefan Ruzitschka <stefan@icepuma.dev>"]
repository = "https://github.com/icepuma/temps"
license = "MIT OR Apache-2.0"
